### ISSUE TITLE
Running "start" project for chapter 3 gives following error

### ISSUE THREAD

**Issue by Amitbhave** [PacktPublishing/Flutter-UI-Projects-for-iOS-Android-and-Web#2]
No AndroidManifest.xml file found.

Quick fix:
Run following command ->
"flutter create ."

**Comment by chimon2000** [comment]
This was by design.  

The reason is that native dependencies break much more often than code, so hypothetically if a user is using Flutter v5 there's always a chance that they could try to run the example and it is broken.
