### ISSUE TITLE
Error in todos_with_provider (in chapter 3)

### ISSUE THREAD

**Issue by Amitbhave** [PacktPublishing/Flutter-UI-Projects-for-iOS-Android-and-Web#3]
Currently in todo_view.dart file, "context.select((TodosController m) => m.todos);" is used for listening to changes for todos list.
But this list is declared as final, and createTodo function adds todo to this list, effectively the Todo List object doesn't change and hence the component is not rebuilt.
Simple fix:
Make todo list non-final, and replace createTodo function with following:
```
Future<void> createTodo(Todo todo) async {
    _todos = [..._todos, todo];
    notifyListeners();
  }
```

Reference: https://github.com/rrousselGit/provider/issues/560

cc: @albertodev01 @chimon2000

**Comment by chimon2000** [comment]
The actual issue was using `read` instead of `watch`.  The former does not update the UI when changes occur @Amitbhave
